export const USER_LOGIN_REQUEST = 'USER_LOG_IN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOG_IN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'
